### ISSUE TITLE
no bower support

### ISSUE THREAD

**Issue by NoeelMoeskops** [MartijnKeesmaat/Project-Axis#1]
Yo martino,

nicé css class. Je moet het publiceren op [bower](https://bower.io/docs/creating-packages/#register). Het ziet er super uitgebreid uit en nettjes uit. Zelfs heel veel documentatie enzo. Heb je alles zelf gescherven? En is dit deel van je stage of doe je dit thuis? Het is heel vergelijkbaar met dingen zoals bootstrap enzo. Je zou eigenlijk een soort vergelijkings tabel moeten maken waarom ik voor axis zou moeten kiesen en niet voor bootstap of material design ofzo. Anyway super mooi!

**Comment by MartijnKeesmaat** [comment]
Hey Noeël,

Goede suggestie om het op bower te publiceren. Dit is een side-project waar ik mee bezig ben waarbij ik keek naar "wat kan er verbetert worden in mijn huidige front-end workflow". 

Hier kwamen dingen uit zoals een standaard project-structuur te maken zodat ik sneller kan beginnen met elk project. 

En mijn code beter te organiseren door gebruik te maken van [BEM](https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/),  een [SMACSS](https://smacss.com/) geïnspireerde structuur toe te passen en betere [comments](https://github.com/MartijnKeesmaat/Axis/wiki/Organizing-code-with-comments) te gebruiken.

**Comment by NoeelMoeskops** [comment]
Het ziet er in ieder geval veel beloverd uit.
bedankt voor het sturen van BEM en SMACSS ziet er intresant uit, ga ik een keer lezen.

Ga je ook naast css, html templates maken ofzo? Je kan dan misschien gebruik maken van [HTML template](https://developer.mozilla.org/en/docs/Web/HTML/Element/template) Het word alleen [niet ondersteund door IE](http://caniuse.com/#search=template) :(. Of zoiets als [html imports](https://www.html5rocks.com/en/tutorials/webcomponents/imports/) Maar dat word alleen maar door [chrome en Opera ondersteund](http://caniuse.com/#search=html%20import). Dus misschien word ik iets te enthousiast. Je kan [Angular](https://angularjs.org/) gebruiken dat word tenminsten wel gewoon ondersteund. Ga er je ook ondersteuning voor een CMS in bouwen?

Als je van plan bent om het pakket uit tebreiden buiten css wil ik best helpen. [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM) zou hier ook idiaal voor zijn, maar helaas ik het net als de andren technieken die ik stuur [nog niet bruikbaar](http://caniuse.com/#search=shadow%20dom) :(.

**Comment by MartijnKeesmaat** [comment]
Ik heb ff gekeken om Axis aan Bower toe te voegen, maar Bower is alleen voor plugins of frameworks en Axis is meer een boilerplate. Je kan nu wel `bower install axis` doen maar dan komt alles in een bower_components folder.

**Comment by NoeelMoeskops** [comment]
hmmm, juist ja. Ik dacht dat het juist het idee was dat Axis een libary was. Je kan dan ook [Composer](https://getcomposer.org/) gebruiken. En anders gewoon `git clone http://github.com/MartijnKeesmaat/axis` Maar dan kan je niet met releases werken wat je eigenlijk wel wilt.

**Comment by NoeelMoeskops** [comment]
of je moet een release branch maken

**Comment by NoeelMoeskops** [comment]
Ik denk dat het überhout veel beter is om er wel een libary van te maken. Ik zie er nu ook weinig boilerplate dingen in want je hebt geen dingen zoals html of php erbij. Instaleren via bower is het best. Want je serveert alleen maar css. En dan kan je het ook nog eens updaten, wanneer er een nieuwe versie uitkomt. Want je hele axis pakket is toch eigenlijk allemaal css classen? Dus om het er manual in te plakken is niet de beste methode.
